package de.jensklingenberg.ktorfit.internal

/**
 * This will be implemented by classes that
 * are generated by Ktorfit-Ksp.
 */
public interface KtorfitService {
    public var ktorfitClient: Client

    /**
     * Used to set the [ktorfitClient] at runtime
     */
    public fun setClient(ktorfitClient: Client) {
        this.ktorfitClient = ktorfitClient
    }



}