package de.jensklingenberg.ktorfit.internal

/**
 * This will be implemented by classes that
 * are generated by Ktorfit-Ksp.
 */
public interface KtorfitService {
    /**
     * Used to set the [client] at runtime
     */
    public fun setClient(client: KtorfitClient)
}