name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: input
    id: ktorfit-version
    attributes:
      label: Ktorfit version
      placeholder: ex. 1.x.x
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened and how can we reproduce this issue?
      description: as minimally and precisely as possible please
      placeholder: Give us a nice bullited list of things that lead up to this bug
    validations:
      required: true
  - type: textarea
    id: expexted
    attributes:
      label: What did you expect to happen?
      description: What would happen if everything was going smoothly?
    validations:
      required: true
  - type: textarea
    id: extra-details
    attributes:
      label: Is there anything else we need to know about?
      description: Tell us the rest of the story
    validations:
      required: false
  
