
package de.jensklingenberg.ktorfit

val testFunctionWithGETExpected = """// Generated by Ktorfit
package com.example.api

import de.jensklingenberg.ktorfit.Ktorfit
import de.jensklingenberg.ktorfit.`internal`.FieldData
import de.jensklingenberg.ktorfit.`internal`.FieldType
import de.jensklingenberg.ktorfit.`internal`.HeaderData
import de.jensklingenberg.ktorfit.`internal`.KtorfitClient
import de.jensklingenberg.ktorfit.`internal`.QueryData
import de.jensklingenberg.ktorfit.`internal`.QueryType
import de.jensklingenberg.ktorfit.`internal`.RequestData
import de.jensklingenberg.ktorfit.http.GET

public class _TestServiceImpl(
  private val client: KtorfitClient,
) : TestService {
  public override suspend fun test(): String {
    val requestData = RequestData(method="GET",
        relativeUrl="user",
        qualifiedRawTypeName="kotlin.String") 

    return client.suspendRequest<String, String>(requestData)
  }
}
"""
