name: Publish Gradle Plugin

on:
  workflow_dispatch:

jobs:
  publish-gradle-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish Gradle Plugin
        run: ./gradlew :ktorfit-gradle-plugin:publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
